### ISSUE TITLE
Login error with passing username and password

### ISSUE THREAD

**Issue by AltarIbnL** [essentialkaos/go-crowd#57]
# Description
I am trying to verify a user in crowd and I want to automate it using such api define in go-crowd:
>  func (*API) Login

But unfortunately, go-crowd return error with EOF. I've tried to use crowd's own restful api and it returns the user's information correctly, so I'm wondering if there's an error in the logic of the Login code that needs to be modified.

I pass command with 

> curl -i -u appname:appspassword --data '{"value": "mypasswod"}' http://localhost:8095/crowd/rest/usermanagement/1/authentication?username=username --header 'Content-Type: application/json' --header 'Accept: application/json' 

It return 
```code
HTTP/1.1 200 OK
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'
X-Embedded-Crowd-Version: Crowd/5.0.5
X-Crowd-User-Management-Version: 1.4
Set-Cookie: crowd.rememberme.token=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Path=/crowd; HttpOnly
Set-Cookie: JSESSIONID=1089498EB458FC83B9DAC71BC47BB5FA; Path=/crowd; HttpOnly
vary: accept-encoding
Content-Type: application/xml;charset=UTF-8
Content-Length: 2340
Date: Sun, 18 Aug 2024 14:28:54 GMT

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><user expand="attributes" name="username"><link href="http://localhost:8095/crowd/rest/usermanagement/1/user?username=username"
```

**System info:**

* **Version (v3.2.2):** 
* **Go version (`1.22.6`):** 

**Steps to reproduce:**

```code
crowdApi, err := crowd.NewCrowdService(crowdconfig.Url, crowdconfig.Name, crowdconfig.Password)
	if err != nil {
		return nil, status.Error(500, err.Error())
	}

user, err := crowdApi.Api.Login(username, password)
	if err != nil {
		fmt.Println("Error", err)
		return false, "", err
	}
```
return
```code
Error EOF
```

**Comment by andyone** [comment]
Hi! What value do you use for `crowdconfig.Url`?

**Comment by AltarIbnL** [comment]
> Hi! What value do you use for `crowdconfig.Url`?

I use my server IP:port that deploy crowd like http://10.150.0.85:8095/crowd
I can successful get userinfo  with  func (*API) GetUser, but failed in func (*API) Login
